name: WPCS Check

on: pull_request

jobs:
  phpcs:
      name: WPCS
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
          with:
            fetch-depth: 0
        - name: WPCS Check
          uses: 10up/wpcs-action@fix/wordpress-standard
          with:
            enable_warnings: true
            standard: WordPress
            only_changed_lines: true
